#include "fleet/support/json.h"
#include "fleet/support/files.h"
#include "fleet/workflow/workflow_data.h"
#include "fleet/task/task.h"
#include <ctype.h>
#include <stdlib.h>
#include <string.h>

bool wd_name(const char *name) {
    const char *p;
    if (!name || *name < 'a' || *name > 'z' || strlen(name) > 64) return false;
    for (p = name; *p; p++) if (!strchr("abcdefghijklmnopqrstuvwxyz0123456789_-", *p)) return false;
    return true;
}
static bool declarations(json_object *map, bool input) {
    const char *const keys[] = {"path", "type", "max_bytes", "sha256", "source", NULL};
    if (!json_object_is_type(map, json_type_object) || json_object_object_length(map) > (int)WD_NAMES) return false;
    json_object_object_foreach(map, name, value) {
        const char *type = f_string(value, "type"), *digest = f_string(value, "sha256"), *source = f_string(value, "source");
        json_object *bound = f_field(value, "max_bytes"); int64_t bytes = json_object_get_int64(bound);
        if (!wd_name(name) || !task_keys(value, keys) || !task_path(f_string(value, "path")) || !type ||
            !json_object_is_type(bound, json_type_int) || bytes < 1 || bytes > TASK_FILE_LIMIT ||
            (f_field(value, "sha256") && (!input || !task_hex(digest, 64))) ||
            (f_field(value, "source") && (!input || !source || (strcmp(source, "repository") && strcmp(source, "task"))))) return false;
        if (strcmp(type, "file")) {
            if (bytes > WD_LIMIT || (strcmp(type, "object") && strcmp(type, "array") && strcmp(type, "string") &&
                strcmp(type, "number") && strcmp(type, "boolean"))) return false;
        }
    }
    return true;
}
/* The graph is generated by the existing strict workflow reader. Keep only the
 * fields needed to validate references; this is not another scheduler. */
static json_object *graph_read(const char *path) {
    char *text = f_read(path, F_LIMIT), *line, *save = NULL; json_object *graph = json_object_new_object();
    if (!text || !graph) goto bad;
    for (line = strtok_r(text, "\n", &save); line; line = strtok_r(NULL, "\n", &save)) {
        char *field, *fields = NULL, *name, *kind, *needs; json_object *step;
        field = strtok_r(line, "\t", &fields);
        if (!field || strcmp(field, "step")) continue;
        name = strtok_r(NULL, "\t", &fields); kind = strtok_r(NULL, "\t", &fields); needs = strtok_r(NULL, "\t", &fields);
        if (!wd_name(name) || !kind || !needs || f_field(graph, name) || json_object_object_length(graph) >= (int)WD_STEPS) goto bad;
        step = json_object_new_object(); f_string_add(step, "kind", kind); f_string_add(step, "needs", needs);
        json_object_object_add(graph, name, step);
    }
    free(text); return graph;
bad:
    free(text); json_object_put(graph); return NULL;
}
static bool dependency(json_object *graph, const char *step, const char *producer) {
    const char *needs = f_string(f_field(graph, step), "needs"); size_t n = strlen(producer);
    if (!needs) return false;
    while (*needs) {
        const char *end = strchr(needs, ','); size_t length = end ? (size_t)(end - needs) : strlen(needs);
        if (length == n && !strncmp(needs, producer, n)) return true;
        if (!end) break;
        needs = end + 1;
    }
    return false;
}
static bool references(json_object *manifest, json_object *graph, const char *step, json_object *inputs) {
    const char *const keys[] = {"input", "step", "output", NULL};
    if (!json_object_is_type(inputs, json_type_object) || json_object_object_length(inputs) > (int)WD_NAMES) return false;
    json_object_object_foreach(inputs, name, value) {
        const char *input = f_string(value, "input"), *producer = f_string(value, "step"), *output = f_string(value, "output");
        if (!wd_name(name) || !task_keys(value, keys)) return false;
        if (input) {
            if (!wd_name(input) || f_field(value, "step") || f_field(value, "output") || !f_field(f_field(manifest, "inputs"), input)) return false;
        } else {
            if (f_field(value, "input") || !wd_name(producer) || !wd_name(output) || !dependency(graph, step, producer) ||
                !f_field(f_field(f_field(f_field(manifest, "steps"), producer), "outputs"), output)) return false;
        }
    }
    return true;
}
json_object *wd_manifest(const char *manifest, const char *graph_path) {
    const char *const keys[] = {"schema_version", "inputs", "steps", NULL};
    const char *const step_keys[] = {"inputs", "outputs", NULL};
    json_object *data = f_read_json(manifest, WD_LIMIT), *graph = graph_read(graph_path), *steps;
    if (!data || !graph || !task_keys(data, keys) || !f_number_is(data, "schema_version", 1) ||
        !declarations(f_field(data, "inputs"), true)) goto bad;
    steps = f_field(data, "steps");
    if (!json_object_is_type(steps, json_type_object) || json_object_object_length(steps) > (int)WD_STEPS) goto bad;
    json_object_object_foreach(steps, name, value) {
        const char *kind = f_string(f_field(graph, name), "kind");
        if (!wd_name(name) || !kind || !task_keys(value, step_keys) ||
            (f_field(value, "inputs") && !references(data, graph, name, f_field(value, "inputs"))) ||
            (f_field(value, "outputs") && ((strcmp(kind, "exec") && strcmp(kind, "task")) || !declarations(f_field(value, "outputs"), false)))) goto bad;
    }
    json_object_put(graph); return data;
bad:
    json_object_put(graph); json_object_put(data); return NULL;
}
