#!/usr/bin/env python3
import csv,json,math,hashlib,os,sys
inp=os.environ['HYDRA_WORKFLOW_INPUTS_DIR']; out=os.environ['HYDRA_WORKFLOW_OUTPUTS_DIR']; report=json.load(open(os.path.join(inp,'subject'))); jobs=list(csv.DictReader(open(os.path.join(inp,'jobs'))))
def sim(policy):
 j=[{'id':r['id'],'a':int(r['arrival']),'d':int(r['duration']),'o':i} for i,r in enumerate(jobs)]; t=0;s=[]
 while j:
  q=[x for x in j if x['a']<=t]
  if not q:t=min(x['a'] for x in j);q=[x for x in j if x['a']<=t]
  x=min(q,key=lambda z:(z['a'],z['o']) if policy=='FCFS' else (z['d'],z['a'],z['o']));j.remove(x); st=t;t+=x['d'];s.append({'id':x['id'],'start':st,'finish':t,'wait':st-x['a'],'turnaround':t-x['a']})
 v=[x['turnaround'] for x in s];w=[x['wait'] for x in s];return {'schedule':s,'mean_wait':sum(w)/len(w),'mean_turnaround':sum(v)/len(v),'p95_turnaround':sorted(v)[math.ceil(.95*len(v))-1],'max_wait':max(w),'worst_wait_job':max(s,key=lambda x:x['wait'])['id']}
checks=[]; sha=hashlib.sha256(open(os.path.join(inp,'jobs'),'rb').read()).hexdigest(); checks += [('data_hash',report['provenance']['data_sha256']==sha),('locations',all(x.startswith('/') for x in report.get('claim_locations',[]))),('unsupported_claim_guard',report['claims']['limits']==['12 synthetic jobs','one server','exact known durations','non-preemptive','no production evidence'])]
for k in ('FCFS','SJF'): checks.append((k,report['policies'][k]==sim(k)))
valid=all(x[1] for x in checks); raw={'verdict':'pass' if valid else 'fail','recommendation':report['claims'].get('recommendation'),'checks':[k for k,v in checks if not v] or 'all quantities recomputed'}; rh=hashlib.sha256(json.dumps(raw,sort_keys=True,separators=(',',':')).encode()).hexdigest(); data=json.load(open(os.environ['HYDRA_WORKFLOW_VALIDATION_FILE']))['data']; subject=hashlib.sha256(open(os.path.join(inp,'subject'),'rb').read()).hexdigest(); obs=[{'id':'research-check','raw':raw,'raw_sha256':rh}]; rec={'obligation_id':'research-check','subject_manifest_sha256':subject,'validator_identity':'research-checker-v3','validator_recipe_sha256':data['check-recipe'],'invocation':{'argv':['python3','research_check.py'],'exit_code':0 if valid else 1},'environment':{'host':'local','toolchain':'python3'},'case_inventory':['FCFS','SJF','recommendation'],'observations':obs,'raw_evidence_sha256':hashlib.sha256(json.dumps(obs,sort_keys=True,separators=(',',':')).encode()).hexdigest(),'counts':{'executed':1,'failed':0 if valid else 1,'skipped':0},'limitations':['bounded finite trace']}; result={'schema_version':3,'execution_status':'completed','evidence_status':'valid' if valid else 'invalid','domain_verdict':'pass' if valid else 'fail','verdict':'pass' if valid else 'fail','subject_sha256':subject,'validator_sha256':data['check'],'requirements':['means','tails','fairness','recommendation','reproduce','limits'],'evidence':'independent recomputation against jobs.csv','limitations':['bounded finite trace'],'evidence_records':[rec]}; json.dump(result,open(os.path.join(out,'assessment'),'w'),separators=(',',':')); print(json.dumps(result)); sys.exit(0 if valid else 1)
